#!/usr/bin/env python3
"""
scripts/swing_signals.py — Deterministic swing trading signal generator
Reads  public/data/ohlc_*.json
Writes public/data/signals_{id}.json

Signal types:
  GOLDEN_CROSS       — MA20 crossed above MA60 within last 5 bars
  DEATH_CROSS        — MA20 crossed below MA60 within last 5 bars
  RSI_OVERSOLD       — RSI(14) < 30
  RSI_OVERBOUGHT     — RSI(14) > 70
  RSI_RECOVERING     — RSI rising from <40 back toward neutral
  VOLUME_BREAKOUT    — Volume > 2× MA20 AND price ≥ +2%
  VOLUME_SELLOFF     — Volume > 2× MA20 AND price ≤ -2%
  MA20_BOUNCE        — Price bounced off MA20 support (within 3%)
  MA60_BOUNCE        — Price bounced off MA60 major support (within 3%)
  BULLISH_ALIGNMENT  — MA5 > MA20 > MA60 AND price > MA5
  CONTROLLED_ADVANCE — Volume < 60% MA20 AND price change > +1.5% (main-force control)
  MACD_GOLDEN_CROSS  — MACD DIF crossed above DEA
  MACD_DEATH_CROSS   — MACD DIF crossed below DEA
  BB_UPPER_BREAK     — Price breaks above Bollinger upper band
  BB_LOWER_BREAK     — Price touches Bollinger lower band (mean-reversion watch)
  BB_SQUEEZE         — Bollinger bandwidth < 5% (volatility contraction)
  KDJ_GOLDEN_CROSS   — KDJ K crossed above D in oversold zone
  KDJ_DEATH_CROSS    — KDJ K crossed below D in overbought zone
  KDJ_OVERSOLD       — KDJ J < 0 (extreme oversold)
  KDJ_OVERBOUGHT          — KDJ J > 100 (extreme overbought)
  CVD_BEARISH_DIVERGENCE  — Price +>1% but 5-day CVD slope negative (AS model: MM suppression)
  CVD_FLOOR_FORMED        — CVD 1-day drop >20% but 3-day drop <5% (inventory release complete)

Zone values: BULLISH | BEARISH | NEUTRAL | OVERSOLD | OVERBOUGHT

CVD note: Cumulative Volume Delta = Σ daily main_net (大单净流入, 万元) from Eastmoney.
Requires cflow_*.json files generated by fetch_data.py. A-share only.
"""

import json
import glob
import os
from datetime import datetime, timezone

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'public', 'data')


# ── Math helpers ──────────────────────────────────────────────────────────────

def sma(series, n):
    """Simple moving average — list same length as input, None where < n values."""
    result = [None] * len(series)
    for i in range(n - 1, len(series)):
        result[i] = sum(series[i - n + 1:i + 1]) / n
    return result


def ema(series, n):
    """Exponential moving average (seed = SMA of first n values)."""
    result = [None] * len(series)
    if len(series) < n:
        return result
    result[n - 1] = sum(series[:n]) / n
    k = 2.0 / (n + 1)
    for i in range(n, len(series)):
        result[i] = series[i] * k + result[i - 1] * (1.0 - k)
    return result


def rsi(closes, period=14):
    """
    Wilder's RSI — list same length as closes.
    Result[i] is the RSI using closes[0..i].
    First valid value at index = period.
    """
    result = [None] * len(closes)
    if len(closes) < period + 1:
        return result

    changes = [closes[i] - closes[i - 1] for i in range(1, len(closes))]
    gains   = [max(c, 0.0) for c in changes]
    losses  = [abs(min(c, 0.0)) for c in changes]

    avg_gain = sum(gains[:period]) / period
    avg_loss = sum(losses[:period]) / period

    def _rsi_from(ag, al):
        if al == 0:
            return 100.0
        return 100.0 - 100.0 / (1.0 + ag / al)

    result[period] = _rsi_from(avg_gain, avg_loss)

    for i in range(period, len(changes)):
        avg_gain = (avg_gain * (period - 1) + gains[i])  / period
        avg_loss = (avg_loss * (period - 1) + losses[i]) / period
        result[i + 1] = _rsi_from(avg_gain, avg_loss)

    return result


def macd_calc(closes, fast=12, slow=26, signal=9):
    """
    MACD indicator.
    Returns (dif, dea, histogram) — all arrays of same length as closes.
    DIF = EMA(fast) - EMA(slow)
    DEA = EMA(signal) of DIF
    HIST = (DIF - DEA) * 2
    """
    n = len(closes)
    ema_fast = ema(closes, fast)
    ema_slow = ema(closes, slow)

    dif = [None] * n
    for i in range(n):
        if ema_fast[i] is not None and ema_slow[i] is not None:
            dif[i] = ema_fast[i] - ema_slow[i]

    # DEA = EMA(signal) of valid DIF values
    dea  = [None] * n
    hist = [None] * n

    valid_dif_idx = [i for i, v in enumerate(dif) if v is not None]
    if len(valid_dif_idx) < signal:
        return dif, dea, hist

    seed_pos = valid_dif_idx[signal - 1]
    dea[seed_pos] = sum(dif[i] for i in valid_dif_idx[:signal]) / signal

    k_sig = 2.0 / (signal + 1)
    for i in range(seed_pos + 1, n):
        if dif[i] is not None and dea[i - 1] is not None:
            dea[i] = dif[i] * k_sig + dea[i - 1] * (1.0 - k_sig)

    for i in range(n):
        if dif[i] is not None and dea[i] is not None:
            hist[i] = (dif[i] - dea[i]) * 2.0

    return dif, dea, hist


def bollinger_calc(closes, period=20, k=2.0):
    """
    Bollinger Bands.
    Returns (upper, middle, lower) arrays.
    """
    n   = len(closes)
    mid = sma(closes, period)
    upper = [None] * n
    lower = [None] * n

    for i in range(period - 1, n):
        window = closes[i - period + 1:i + 1]
        mean   = mid[i]
        stdev  = (sum((c - mean) ** 2 for c in window) / period) ** 0.5
        upper[i] = mean + k * stdev
        lower[i] = mean - k * stdev

    return upper, mid, lower


def kdj_calc(bars, period=9, m1=3, m2=3):
    """
    KDJ stochastic oscillator.
    bars: list of dicts with 'close', 'high', 'low'.
    Returns (K, D, J) arrays.
    """
    n      = len(bars)
    highs  = [b['high']  for b in bars]
    lows   = [b['low']   for b in bars]
    closes = [b['close'] for b in bars]

    rsv = [None] * n
    for i in range(period - 1, n):
        high_n = max(highs[i - period + 1:i + 1])
        low_n  = min(lows[i  - period + 1:i + 1])
        if high_n == low_n:
            rsv[i] = 50.0
        else:
            rsv[i] = (closes[i] - low_n) / (high_n - low_n) * 100.0

    k_arr = [None] * n
    d_arr = [None] * n
    j_arr = [None] * n

    first = next((i for i, v in enumerate(rsv) if v is not None), None)
    if first is None:
        return k_arr, d_arr, j_arr

    k_arr[first] = 50.0
    d_arr[first] = 50.0

    for i in range(first + 1, n):
        if rsv[i] is None:
            continue
        prev_k = k_arr[i - 1] if k_arr[i - 1] is not None else 50.0
        prev_d = d_arr[i - 1] if d_arr[i - 1] is not None else 50.0
        k_arr[i] = (m1 - 1) / m1 * prev_k + rsv[i] / m1
        d_arr[i] = (m2 - 1) / m2 * prev_d + k_arr[i] / m2

    for i in range(n):
        if k_arr[i] is not None and d_arr[i] is not None:
            j_arr[i] = 3.0 * k_arr[i] - 2.0 * d_arr[i]

    return k_arr, d_arr, j_arr


def cvd_calc(flow_rows):
    """
    Compute Cumulative Volume Delta (CVD) from Eastmoney daily capital flow data.

    flow_rows: list of dicts with 'main_net' (大单净流入, 万元), sorted oldest→newest.
    Returns dict with:
      cvd_series   — list of cumulative CVD values (same length as flow_rows)
      cvd_latest   — most recent CVD absolute value (万元)
      cvd_slope_5d — 5-day linear slope of CVD (change per day, 万元)
      cvd_chg_1d   — 1-day % change in main_net (not CVD): (today - yesterday) / |yesterday|
      cvd_chg_3d   — 3-day % change in main_net sum: (last3 - prior3) / |prior3|
    Returns None if insufficient data (<5 rows with valid main_net).
    """
    # Extract valid main_net values with their indices
    nets = [(i, r.get('main_net')) for i, r in enumerate(flow_rows)
            if r.get('main_net') is not None]
    if len(nets) < 5:
        return None

    # Build cumulative CVD indexed to full length
    n       = len(flow_rows)
    cvd_arr = [None] * n
    running = 0.0
    for i, net in nets:
        running    += net
        cvd_arr[i]  = running

    # Forward-fill any gaps
    last_val = None
    for i in range(n):
        if cvd_arr[i] is not None:
            last_val = cvd_arr[i]
        elif last_val is not None:
            cvd_arr[i] = last_val

    # Drop leading Nones
    valid_cvd = [(i, v) for i, v in enumerate(cvd_arr) if v is not None]
    if len(valid_cvd) < 5:
        return None

    cvd_latest = valid_cvd[-1][1]

    # 5-day slope via simple linear regression on last 5 CVD values
    last5_cvd = [v for _, v in valid_cvd[-5:]]
    n5         = len(last5_cvd)
    xs         = list(range(n5))
    mx, my     = sum(xs) / n5, sum(last5_cvd) / n5
    denom      = sum((x - mx) ** 2 for x in xs)
    cvd_slope_5d = sum((x - mx) * (y - my) for x, y in zip(xs, last5_cvd)) / denom \
                   if denom else 0.0

    # 1-day % change in main_net (last bar vs bar before)
    valid_nets   = [(i, net) for i, net in nets]
    cvd_chg_1d   = None
    cvd_chg_3d   = None
    if len(valid_nets) >= 2:
        today_net, yest_net = valid_nets[-1][1], valid_nets[-2][1]
        if yest_net and abs(yest_net) > 1:
            cvd_chg_1d = (today_net - yest_net) / abs(yest_net) * 100.0

    if len(valid_nets) >= 6:
        last3_sum  = sum(n for _, n in valid_nets[-3:])
        prior3_sum = sum(n for _, n in valid_nets[-6:-3])
        if prior3_sum and abs(prior3_sum) > 1:
            cvd_chg_3d = (last3_sum - prior3_sum) / abs(prior3_sum) * 100.0

    return {
        'cvd_latest':   cvd_latest,
        'cvd_slope_5d': cvd_slope_5d,
        'cvd_chg_1d':   cvd_chg_1d,
        'cvd_chg_3d':   cvd_chg_3d,
    }


# ── Signal engine ─────────────────────────────────────────────────────────────

def compute_signals(ticker, bars, flow_data=None):
    """
    bars:      list of {date, open, high, low, close, volume} sorted oldest→newest.
    flow_data: optional list of {date, main_net, ...} from cflow_*.json (A-share only).
    Returns signals dict or None if insufficient data.
    """
    if len(bars) < 20:
        return None

    closes  = [b['close']  for b in bars]
    volumes = [b['volume'] for b in bars]
    dates   = [b['date']   for b in bars]
    n       = len(bars)

    # ── Indicator arrays ───────────────────────────────────────────────────
    ma5_arr   = sma(closes, 5)
    ma20_arr  = sma(closes, 20)
    ma60_arr  = sma(closes, 60)
    rsi14_arr = rsi(closes, 14)
    vma20_arr = sma(volumes, 20)

    # MACD
    dif_arr, dea_arr, hist_arr = macd_calc(closes)

    # Bollinger Bands
    bb_upper_arr, bb_mid_arr, bb_lower_arr = bollinger_calc(closes)

    # KDJ
    k_arr, d_arr, j_arr = kdj_calc(bars)

    # CVD (optional — A-share only, from cflow_*.json)
    cvd = cvd_calc(flow_data) if flow_data else None

    def at(arr, offset=0):
        idx = n - 1 - offset
        return arr[idx] if (0 <= idx < len(arr) and arr[idx] is not None) else None

    price   = closes[-1]
    ma5     = at(ma5_arr)
    ma20    = at(ma20_arr)
    ma60    = at(ma60_arr)
    rsi_val = at(rsi14_arr)
    vma20   = at(vma20_arr)
    vol_now = volumes[-1]

    dif_curr = at(dif_arr)
    dea_curr = at(dea_arr)
    dif_prev = at(dif_arr, 1)
    dea_prev = at(dea_arr, 1)

    bb_upper  = at(bb_upper_arr)
    bb_mid    = at(bb_mid_arr)
    bb_lower  = at(bb_lower_arr)
    bb_upper1 = at(bb_upper_arr, 1)
    bb_lower1 = at(bb_lower_arr, 1)

    k_curr = at(k_arr)
    d_curr = at(d_arr)
    j_curr = at(j_arr)
    k_prev = at(k_arr, 1)
    d_prev = at(d_arr, 1)

    # ── Price-change helpers ───────────────────────────────────────────────
    def pct_chg(n_bars):
        if n > n_bars:
            p0 = bars[-(n_bars + 1)]['close']
            return round((price - p0) / p0 * 100, 2) if p0 else None
        return None

    prev_close = closes[-2] if n >= 2 else None
    p1d_chg = (price - prev_close) / prev_close * 100 if prev_close else 0

    # ── Signals list ──────────────────────────────────────────────────────
    sigs = []

    # ── 1. Golden / Death Cross (MA20 vs MA60) ─────────────────────────────
    CROSS_WINDOW = 5
    if ma20 is not None and ma60 is not None:
        for k in range(1, min(CROSS_WINDOW + 1, n)):
            pm20 = ma20_arr[n - 1 - k]
            pm60 = ma60_arr[n - 1 - k]
            if pm20 is None or pm60 is None:
                continue
            if pm20 <= pm60 and ma20 > ma60:
                sigs.append({
                    'type': 'GOLDEN_CROSS', 'strength': 'strong',
                    'date': dates[-1], 'bullish': True,
                    'description': {
                        'e': f'MA20 ({ma20:.1f}) crossed above MA60 ({ma60:.1f}) — bullish trend shift',
                        'z': f'MA20({ma20:.1f})上穿MA60({ma60:.1f})金叉看涨',
                    }
                })
                break
            if pm20 >= pm60 and ma20 < ma60:
                sigs.append({
                    'type': 'DEATH_CROSS', 'strength': 'strong',
                    'date': dates[-1], 'bullish': False,
                    'description': {
                        'e': f'MA20 ({ma20:.1f}) crossed below MA60 ({ma60:.1f}) — bearish trend shift',
                        'z': f'MA20({ma20:.1f})下穿MA60({ma60:.1f})死叉看跌',
                    }
                })
                break

    # ── 2. RSI zones ───────────────────────────────────────────────────────
    if rsi_val is not None:
        rsi_prev = at(rsi14_arr, 1)
        if rsi_val < 30:
            sigs.append({
                'type': 'RSI_OVERSOLD',
                'strength': 'strong' if rsi_val < 20 else 'moderate',
                'date': dates[-1], 'bullish': True,
                'description': {
                    'e': f'RSI(14) = {rsi_val:.1f} — oversold, watch for reversal',
                    'z': f'RSI(14)={rsi_val:.1f}，超卖，关注反转信号',
                }
            })
        elif rsi_val > 70:
            sigs.append({
                'type': 'RSI_OVERBOUGHT',
                'strength': 'strong' if rsi_val > 80 else 'moderate',
                'date': dates[-1], 'bullish': False,
                'description': {
                    'e': f'RSI(14) = {rsi_val:.1f} — overbought, watch for exhaustion',
                    'z': f'RSI(14)={rsi_val:.1f}，超买，注意回调风险',
                }
            })
        elif (rsi_prev is not None
              and rsi_prev < 40
              and rsi_val > rsi_prev
              and rsi_val < 55):
            sigs.append({
                'type': 'RSI_RECOVERING', 'strength': 'moderate',
                'date': dates[-1], 'bullish': True,
                'description': {
                    'e': f'RSI recovering {rsi_prev:.1f}→{rsi_val:.1f} — momentum rebuilding',
                    'z': f'RSI从{rsi_prev:.1f}回升至{rsi_val:.1f}，动能修复',
                }
            })

    # ── 3. Volume breakout / selloff ───────────────────────────────────────
    if vma20 is not None and vma20 > 0:
        vol_ratio = vol_now / vma20
        if vol_ratio >= 2.0 and n >= 2:
            if p1d_chg >= 2.0:
                sigs.append({
                    'type': 'VOLUME_BREAKOUT',
                    'strength': 'strong' if vol_ratio >= 3.0 else 'moderate',
                    'date': dates[-1], 'bullish': True,
                    'description': {
                        'e': f'Volume {vol_ratio:.1f}× avg, price +{p1d_chg:.1f}% — buying surge',
                        'z': f'成交量{vol_ratio:.1f}倍均量，股价+{p1d_chg:.1f}%，放量上攻',
                    }
                })
            elif p1d_chg <= -2.0:
                sigs.append({
                    'type': 'VOLUME_SELLOFF',
                    'strength': 'strong' if vol_ratio >= 3.0 else 'moderate',
                    'date': dates[-1], 'bullish': False,
                    'description': {
                        'e': f'Volume {vol_ratio:.1f}× avg, price {p1d_chg:.1f}% — distribution',
                        'z': f'成交量{vol_ratio:.1f}倍均量，股价{p1d_chg:.1f}%，放量下跌',
                    }
                })

    # ── 4. MA20 bounce ─────────────────────────────────────────────────────
    if n >= 3 and ma20 is not None:
        prev_close2 = closes[-2]
        prev_ma20   = ma20_arr[n - 2]
        if (prev_ma20 is not None
                and abs(prev_close2 - prev_ma20) / prev_ma20 < 0.03
                and price > prev_ma20
                and price > prev_close2):
            sigs.append({
                'type': 'MA20_BOUNCE', 'strength': 'moderate',
                'date': dates[-1], 'bullish': True,
                'description': {
                    'e': f'Price bounced off MA20 ({prev_ma20:.1f}) — near-term support held',
                    'z': f'股价从MA20({prev_ma20:.1f})附近反弹，短期支撑有效',
                }
            })

    # ── 5. MA60 bounce ─────────────────────────────────────────────────────
    if n >= 3 and ma60 is not None:
        prev_close2 = closes[-2]
        prev_ma60   = ma60_arr[n - 2]
        if (prev_ma60 is not None
                and abs(prev_close2 - prev_ma60) / prev_ma60 < 0.03
                and price > prev_ma60
                and price > prev_close2):
            sigs.append({
                'type': 'MA60_BOUNCE', 'strength': 'strong',
                'date': dates[-1], 'bullish': True,
                'description': {
                    'e': f'Price bounced off MA60 ({prev_ma60:.1f}) — major support held',
                    'z': f'股价从MA60({prev_ma60:.1f})附近反弹，主要支撑有效',
                }
            })

    # ── 6. BULLISH_ALIGNMENT — MA5 > MA20 > MA60 AND price > MA5 ───────────
    if (ma5 is not None and ma20 is not None and ma60 is not None
            and ma5 > ma20 > ma60 and price > ma5):
        sigs.append({
            'type': 'BULLISH_ALIGNMENT', 'strength': 'strong',
            'date': dates[-1], 'bullish': True,
            'description': {
                'e': f'MA5({ma5:.1f}) > MA20({ma20:.1f}) > MA60({ma60:.1f}), price above all — full bullish alignment',
                'z': f'MA5({ma5:.1f})>MA20({ma20:.1f})>MA60({ma60:.1f})，均线多头排列，趋势强',
            }
        })

    # ── 7. CONTROLLED_ADVANCE — light volume, price rising ─────────────────
    if (vma20 is not None and vma20 > 0 and n >= 2):
        vol_ratio_now = vol_now / vma20
        if vol_ratio_now < 0.6 and p1d_chg > 1.5:
            sigs.append({
                'type': 'CONTROLLED_ADVANCE', 'strength': 'moderate',
                'date': dates[-1], 'bullish': True,
                'description': {
                    'e': f'Price +{p1d_chg:.1f}% on light volume ({vol_ratio_now:.2f}× avg) — controlled accumulation',
                    'z': f'缩量上涨{p1d_chg:.1f}%（量比{vol_ratio_now:.2f}×），主力控盘积累',
                }
            })

    # ── 8. MACD cross ──────────────────────────────────────────────────────
    if (dif_curr is not None and dea_curr is not None
            and dif_prev is not None and dea_prev is not None):
        if dif_prev <= dea_prev and dif_curr > dea_curr:
            above_zero = dif_curr > 0
            sigs.append({
                'type': 'MACD_GOLDEN_CROSS',
                'strength': 'strong' if above_zero else 'moderate',
                'date': dates[-1], 'bullish': True,
                'description': {
                    'e': f'MACD DIF({dif_curr:.3f}) crossed above DEA({dea_curr:.3f})'
                         f' {"above" if above_zero else "below"} zero — bullish momentum',
                    'z': f'MACD DIF({dif_curr:.3f})上穿DEA({dea_curr:.3f})'
                         f'{"零轴上方" if above_zero else "零轴下方"}金叉看涨',
                }
            })
        elif dif_prev >= dea_prev and dif_curr < dea_curr:
            below_zero = dif_curr < 0
            sigs.append({
                'type': 'MACD_DEATH_CROSS',
                'strength': 'strong' if below_zero else 'moderate',
                'date': dates[-1], 'bullish': False,
                'description': {
                    'e': f'MACD DIF({dif_curr:.3f}) crossed below DEA({dea_curr:.3f})'
                         f' {"below" if below_zero else "above"} zero — bearish momentum',
                    'z': f'MACD DIF({dif_curr:.3f})下穿DEA({dea_curr:.3f})'
                         f'{"零轴下方" if below_zero else "零轴上方"}死叉看跌',
                }
            })

    # ── 9. Bollinger Band signals ──────────────────────────────────────────
    if bb_upper is not None and bb_lower is not None and bb_mid is not None:
        bandwidth = (bb_upper - bb_lower) / bb_mid * 100.0

        # Upper breakout
        if (prev_close is not None and bb_upper1 is not None
                and prev_close <= bb_upper1 and price > bb_upper):
            sigs.append({
                'type': 'BB_UPPER_BREAK', 'strength': 'moderate',
                'date': dates[-1], 'bullish': True,
                'description': {
                    'e': f'Price ({price:.1f}) broke above Bollinger upper ({bb_upper:.1f}) — momentum breakout',
                    'z': f'股价({price:.1f})突破布林上轨({bb_upper:.1f})，动能突破',
                }
            })

        # Lower touch (mean reversion watch)
        if (prev_close is not None and bb_lower1 is not None
                and prev_close >= bb_lower1 and price < bb_lower):
            sigs.append({
                'type': 'BB_LOWER_BREAK', 'strength': 'moderate',
                'date': dates[-1], 'bullish': True,
                'description': {
                    'e': f'Price ({price:.1f}) touched Bollinger lower ({bb_lower:.1f}) — oversold, mean reversion watch',
                    'z': f'股价({price:.1f})触及布林下轨({bb_lower:.1f})，超卖，关注均值回归',
                }
            })

        # Squeeze — bandwidth narrowing (volatility contraction)
        if bandwidth < 5.0:
            bb_upper5 = at(bb_upper_arr, 5)
            bb_lower5 = at(bb_lower_arr, 5)
            bb_mid5   = at(bb_mid_arr,   5)
            if (bb_upper5 is not None and bb_lower5 is not None and bb_mid5 is not None):
                bw5 = (bb_upper5 - bb_lower5) / bb_mid5 * 100.0
                if bw5 > bandwidth * 1.3:
                    sigs.append({
                        'type': 'BB_SQUEEZE', 'strength': 'moderate',
                        'date': dates[-1], 'bullish': True,
                        'description': {
                            'e': f'Bollinger width {bandwidth:.1f}% (was {bw5:.1f}%) — squeeze, pending directional breakout',
                            'z': f'布林带收窄至{bandwidth:.1f}%（前5日{bw5:.1f}%），波动收缩，方向性突破即将来临',
                        }
                    })

    # ── 10. KDJ signals ────────────────────────────────────────────────────
    if k_curr is not None and d_curr is not None:

        # KDJ Golden Cross in oversold zone
        if (k_prev is not None and d_prev is not None
                and k_prev <= d_prev and k_curr > d_curr and k_curr < 50):
            sigs.append({
                'type': 'KDJ_GOLDEN_CROSS',
                'strength': 'strong' if k_curr < 30 else 'moderate',
                'date': dates[-1], 'bullish': True,
                'description': {
                    'e': f'KDJ K({k_curr:.1f}) crossed above D({d_curr:.1f}) in oversold — reversal signal',
                    'z': f'KDJ K({k_curr:.1f})上穿D({d_curr:.1f})，超卖区金叉看涨',
                }
            })

        # KDJ Death Cross in overbought zone
        elif (k_prev is not None and d_prev is not None
              and k_prev >= d_prev and k_curr < d_curr and k_curr > 50):
            sigs.append({
                'type': 'KDJ_DEATH_CROSS',
                'strength': 'strong' if k_curr > 70 else 'moderate',
                'date': dates[-1], 'bullish': False,
                'description': {
                    'e': f'KDJ K({k_curr:.1f}) crossed below D({d_curr:.1f}) in overbought — reversal signal',
                    'z': f'KDJ K({k_curr:.1f})下穿D({d_curr:.1f})，超买区死叉看跌',
                }
            })

        # J extreme values
        if j_curr is not None:
            if j_curr < 0:
                sigs.append({
                    'type': 'KDJ_OVERSOLD', 'strength': 'strong',
                    'date': dates[-1], 'bullish': True,
                    'description': {
                        'e': f'KDJ J={j_curr:.1f} (extreme <0) — high-probability reversal zone',
                        'z': f'KDJ J={j_curr:.1f}极度超卖，高概率反转区间',
                    }
                })
            elif j_curr > 100:
                sigs.append({
                    'type': 'KDJ_OVERBOUGHT', 'strength': 'strong',
                    'date': dates[-1], 'bullish': False,
                    'description': {
                        'e': f'KDJ J={j_curr:.1f} (extreme >100) — high pullback risk',
                        'z': f'KDJ J={j_curr:.1f}极度超买，回调风险高',
                    }
                })

    # ── 11. CVD signals (A-share only, requires cflow data) ───────────────
    if cvd is not None:
        slope   = cvd['cvd_slope_5d']
        chg_1d  = cvd['cvd_chg_1d']
        chg_3d  = cvd['cvd_chg_3d']

        # CVD_BEARISH_DIVERGENCE: price rising but cumulative buying pressure declining
        # AS model interpretation: market-maker is suppressing price while offloading inventory
        if slope is not None and slope < 0 and p1d_chg > 1.0:
            sigs.append({
                'type': 'CVD_BEARISH_DIVERGENCE',
                'strength': 'strong' if slope < -cvd['cvd_latest'] * 0.05 else 'moderate',
                'date': dates[-1], 'bullish': False,
                'description': {
                    'e': (f'Price +{p1d_chg:.1f}% but CVD 5-day slope={slope:+.0f} 万元/day — '
                          f'MM suppression: inventory offload in progress'),
                    'z': (f'价格涨{p1d_chg:.1f}%但CVD 5日斜率={slope:+.0f}万元/日，'
                          f'做市商压制价格消化库存，警惕砸盘'),
                }
            })

        # CVD_FLOOR_FORMED: sharp single-day CVD drop but 3-day stabilized
        # AS model interpretation: inventory release complete, potential bounce
        if (chg_1d is not None and chg_3d is not None
                and chg_1d < -20.0 and chg_3d > -5.0):
            sigs.append({
                'type': 'CVD_FLOOR_FORMED',
                'strength': 'moderate',
                'date': dates[-1], 'bullish': True,
                'description': {
                    'e': (f'CVD 1-day drop {chg_1d:.1f}% but 3-day change {chg_3d:+.1f}% — '
                          f'inventory release complete, watch for reversal'),
                    'z': (f'CVD单日暴跌{chg_1d:.1f}%但3日变化{chg_3d:+.1f}%趋稳，'
                          f'做市商库存释放完毕，关注反弹机会'),
                }
            })

    # ── Zone classification ───────────────────────────────────────────────
    if rsi_val is not None and rsi_val < 30:
        zone = 'OVERSOLD'
    elif rsi_val is not None and rsi_val > 70:
        zone = 'OVERBOUGHT'
    elif (ma20 is not None and ma60 is not None
          and ma20 > ma60 and price > ma20):
        zone = 'BULLISH'
    elif (ma20 is not None and ma60 is not None
          and ma20 < ma60 and price < ma20):
        zone = 'BEARISH'
    else:
        zone = 'NEUTRAL'

    # ── Entry / exit zones ────────────────────────────────────────────────
    bullish_sigs = [s for s in sigs if s['bullish']]
    bearish_sigs = [s for s in sigs if not s['bullish']]

    entry_types = {
        'RSI_OVERSOLD', 'RSI_RECOVERING', 'GOLDEN_CROSS',
        'MA20_BOUNCE', 'MA60_BOUNCE', 'VOLUME_BREAKOUT',
        'BULLISH_ALIGNMENT', 'CONTROLLED_ADVANCE',
        'MACD_GOLDEN_CROSS', 'BB_LOWER_BREAK', 'BB_SQUEEZE',
        'KDJ_GOLDEN_CROSS', 'KDJ_OVERSOLD',
        'CVD_FLOOR_FORMED',
    }
    exit_types = {
        'RSI_OVERBOUGHT', 'DEATH_CROSS', 'VOLUME_SELLOFF',
        'MACD_DEATH_CROSS', 'BB_UPPER_BREAK',
        'KDJ_DEATH_CROSS', 'KDJ_OVERBOUGHT',
        'CVD_BEARISH_DIVERGENCE',
    }

    entry_zone = zone == 'OVERSOLD' or any(s['type'] in entry_types for s in bullish_sigs)
    exit_zone  = zone == 'OVERBOUGHT' or any(s['type'] in exit_types for s in bearish_sigs)

    # ── Vol ratio ─────────────────────────────────────────────────────────
    vol_ratio_val = round(vol_now / vma20, 2) if (vma20 and vma20 > 0) else None

    # ── Bollinger bandwidth ───────────────────────────────────────────────
    bb_bandwidth = None
    if bb_upper is not None and bb_lower is not None and bb_mid is not None:
        bb_bandwidth = round((bb_upper - bb_lower) / bb_mid * 100.0, 2)

    return {
        'ticker':       ticker,
        'generated_at': datetime.now(timezone.utc).strftime('%Y-%m-%d'),
        'price':        price,
        'zone':         zone,
        'entry_zone':   entry_zone,
        'exit_zone':    exit_zone,
        'signals':      sigs,
        'signal_count': {
            'bullish': len(bullish_sigs),
            'bearish': len(bearish_sigs),
            'total':   len(sigs),
        },
        'indicators': {
            # Moving averages
            'ma5':           round(ma5,  2) if ma5  is not None else None,
            'ma20':          round(ma20, 2) if ma20 is not None else None,
            'ma60':          round(ma60, 2) if ma60 is not None else None,
            # RSI
            'rsi14':         round(rsi_val, 1) if rsi_val is not None else None,
            # Volume
            'vol_ma20':      round(vma20)      if vma20   is not None else None,
            'vol_ratio':     vol_ratio_val,
            # Price relative to MAs
            'price_vs_ma20': round((price - ma20) / ma20 * 100, 2) if ma20 else None,
            'price_vs_ma60': round((price - ma60) / ma60 * 100, 2) if ma60 else None,
            # Price changes
            'change_1d':     pct_chg(1),
            'change_5d':     pct_chg(5),
            'change_20d':    pct_chg(20),
            # MACD
            'macd_dif':      round(dif_curr,  4) if dif_curr  is not None else None,
            'macd_dea':      round(dea_curr,  4) if dea_curr  is not None else None,
            'macd_hist':     round(at(hist_arr), 4) if at(hist_arr) is not None else None,
            # Bollinger Bands
            'bb_upper':      round(bb_upper, 2) if bb_upper is not None else None,
            'bb_mid':        round(bb_mid,   2) if bb_mid   is not None else None,
            'bb_lower':      round(bb_lower, 2) if bb_lower is not None else None,
            'bb_bandwidth':  bb_bandwidth,
            # KDJ
            'kdj_k':         round(k_curr, 1) if k_curr is not None else None,
            'kdj_d':         round(d_curr, 1) if d_curr is not None else None,
            'kdj_j':         round(j_curr, 1) if j_curr is not None else None,
            # CVD (A-share only — None for HK)
            'cvd_latest':    round(cvd['cvd_latest'])    if cvd else None,
            'cvd_slope_5d':  round(cvd['cvd_slope_5d'])  if cvd else None,
            'cvd_chg_1d':    round(cvd['cvd_chg_1d'],  1) if cvd and cvd['cvd_chg_1d']  is not None else None,
            'cvd_chg_3d':    round(cvd['cvd_chg_3d'],  1) if cvd and cvd['cvd_chg_3d']  is not None else None,
        },
    }


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    pattern = os.path.join(DATA_DIR, 'ohlc_*.json')
    files   = sorted(glob.glob(pattern))

    if not files:
        print('[swing_signals] No ohlc_*.json files found — skipping.')
        return

    print(f'[swing_signals] Found {len(files)} OHLC file(s)')

    for fpath in files:
        fname   = os.path.basename(fpath)
        safe_id = fname[len('ohlc_'):-len('.json')]

        try:
            with open(fpath, 'r', encoding='utf-8') as f:
                raw = json.load(f)

            ticker = raw.get('ticker', safe_id.replace('_', '.'))
            bars   = raw.get('data', [])

            if not bars:
                print(f'  [skip] {fname} — empty data array')
                continue

            # Load matching capital flow data if available (A-share only)
            flow_data = None
            cflow_path = os.path.join(DATA_DIR, f'cflow_{safe_id}.json')
            if os.path.exists(cflow_path):
                try:
                    with open(cflow_path, 'r', encoding='utf-8') as cf:
                        cflow_json = json.load(cf)
                    flow_data = cflow_json.get('data', [])
                except Exception:
                    pass

            result = compute_signals(ticker, bars, flow_data=flow_data)
            if result is None:
                print(f'  [skip] {fname} — need ≥20 bars (have {len(bars)})')
                continue

            out_path = os.path.join(DATA_DIR, f'signals_{safe_id}.json')
            with open(out_path, 'w', encoding='utf-8') as f:
                json.dump(result, f, ensure_ascii=False, indent=2)

            z   = result['zone']
            sc  = result['signal_count']
            ind = result['indicators']
            rsi_s  = f"RSI={ind['rsi14']}"    if ind['rsi14']    else 'RSI=n/a'
            macd_s = f"MACD={ind['macd_dif']}" if ind['macd_dif'] else ''
            kdj_s  = f"KDJ-J={ind['kdj_j']}"  if ind['kdj_j']    else ''
            cvd_s  = (f"CVD-slope={ind['cvd_slope_5d']:+.0f}" if ind.get('cvd_slope_5d') is not None else '')
            extra  = '  '.join(x for x in [macd_s, kdj_s, cvd_s] if x)
            print(f'  ✓ {ticker:16s}  price={result["price"]:>8.2f}  zone={z:<11s}  '
                  f'{rsi_s}  {extra}  signals={sc["bullish"]}↑/{sc["bearish"]}↓')

        except Exception as exc:
            print(f'  [error] {fname}: {exc}')

    print('[swing_signals] Complete.')


if __name__ == '__main__':
    main()
